### PR TITLE
Install `yargs` for parsing arguments instead

### PR DESCRIPTION
**Pull request by cursedstuff**
When it comes to CLI arg-parsing, almost no other library can beat [yargs](npmjs.com/package/yargs), and if this is to be considered a serious project you should add more options and configuration. This of course requires parsing, and yargs can do it all.
- cursorsdottsx's alt

### CODE REVIEW

**Comment by GmBodhi** [comment]
I'm not sure, why we need that package. Cuz it'll be like adding a dependency, for nothing. As of now, we don't have any cli args or commands other than the default one. So I think it'll be better to have this when we plan for new commands.

**Comment by cursedstuff** [comment]
Plan ahead, you don't have to add this package now, I'm just saying that it'd be a great candidate if you are going to ever add more features.

**Comment by cursedstuff** [comment]
BTW I'm busy transpiling this to TypeScript. Stay tuned.

**Comment by GmBodhi** [comment]
We will use this package when we plan for new commands or args.

**Pull request closed without merging**
