### PR TITLE
Convert to TypeScript 

### PR DESCRIPTION
**Pull request by cursedstuff**
Project converted to TypeScript. Depending on your configuration and environment there might be some things you still need to sort out, but I think I got most of it done.

### CODE REVIEW

**Comment by cursedstuff** [comment]
Oh no... Did you accidentally commit node_modules 💯 
Screenshot 2021-09-24 1 38 44 PM

**Comment by cursedstuff** [comment]
Screw you LGTM bot this is TypeScript >:

**Comment by CodyJasonBennett** [comment]
Please contact library authors before making major changes to their projects. This will educate how and whether this should be implemented and greatly help review.

**Comment by cursedstuff** [comment]
Oh I have, on Discord. I'm an alt of another account. :)

**Comment by cursorsdottsx** [comment]
Good job, alt account! I'm proud of you.

**Pull request closed without merging**
